version: '3.1'

services:
  dimplom:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      MONGO_URL: "mongodb://root:example@mongo:27017/"
    command: python3 /app/Diplom.py

  mongo:
    image: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - './data:/data/db'